### ISSUE TITLE
Endless buffs randomly start to flicker in Multiplayer

### ISSUE THREAD

**Issue by DBotThePony** [Pbone3/PboneUtils#1]
They appear to flick on/off on each game frame, and happen only when getting in "update proximity" or something with another player on server. However, it does happen only when close to one specific player, when I come closer to second player on server issue doesn't appear.

"Endless Buff Toggler" is empty when this issue occurs.

[Video](https://icf.dbotthepony.ru/2021/05/25/vBmSEf8COP.webm)

**Comment by Pbone3** [comment]
This has been fixed in v1.1.0.
