### ISSUE TITLE
[Suggestion/Fix] 1.4-ify "The Master Plan" item 

### ISSUE THREAD

**Issue by SimoneG97** [Pbone3/PboneUtils#21]
I just noticed the item "The Master Plan" which combines all endless liquid stuff is made with your modded bottomless lava bucket / sponge. But it uses vanilla bottomless water bucket / sponge.
Is this mod available for 1.3 too? In that case it would explain why it doesn't use the vanilla bottomless lava bucket / sponge.

To put it simply, those modded bottomless lava bucket and lava absorbant sponge are kinda useless since they have the same behaviour as the vanilla ones, so I would suggest to simply remove them and add the recipe to craft the vanilla versions.

**Comment by pbone64** [comment]
Fixed with [PboneUtils@119fa1a](https://github.com/Pbone3/PboneUtils/commit/119fa1a580f38f7246c37fa464941327b8163f31)
