### ISSUE TITLE
needs to be updated to current stable version

### ISSUE THREAD

**Issue by goldjojo** [Pbone3/PboneUtils#35]
neither pbone's Utilities or pbone Lib work as of tmodloader v2022.5.103.14
they need to be updated to the current stable version because they cannot be used at the moment
![dotnet_ckYOseJNuT](https://user-images.githubusercontent.com/46782357/172006886-1a379235-a8b2-4f03-979b-be90a7d44620.png)
![dotnet_k7cOUJPy2a](https://user-images.githubusercontent.com/46782357/172006910-57e96d5b-21bf-409d-ae51-52341d5752ae.png)
_these screenshots were taken with only the pbone mods enabled, so it is not a mod conflict problem_

**Comment by pbone64** [comment]
An update for this should be released within the next few minutes

**Comment by D3V1N94** [comment]
![Screenshot 2022-06-06 201152](https://user-images.githubusercontent.com/106995941/172220639-fa8caa87-e4d4-4279-9b6b-0093b1986c92.png)

Still cannot use Phonesutils because an Error 

please fix it in a few days 

cannot play without it such a good mod

**Comment by pbone64** [comment]
You haven't updated your mod.

**Comment by D3V1N94** [comment]
oh shit got an update now ... :O thanks man !
