### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by SomeGuy05** [Pbone3/PboneUtils#37]
Even when the settings for the NPC's are disabled, the mysterious trader seems to still appear. I also noticed that even with the ammo setting off, the items are still available.

As someone else pointed out, the text is also a bit broken.

I really like your mod and hope you can get it fixed when you have time 👍

**Comment by Rijam** [comment]
The text has been fixed in v1.2.15
The toggles for the Town NPCs and items, as well as a bunch of other things, will be fixed in the next update.
