### ISSUE TITLE
CensusCompatability.cs

### ISSUE THREAD

**Issue by Lin-cat** [Pbone3/PboneUtils#9]
how to translate "Defeat Eater of Worlds/Brain of Cthulhu" and"Randomly arrives in the morning and leaves at night, after King Slime or Eye of Cthulhu"

**Comment by Pbone3** [comment]
Oh jeez, I forgot to make those translation keys. I'll fix that and let you know when it's done

**Comment by Pbone3** [comment]
I've pushed a commit that moves it to en-US.lang. Sorry for not seeing this issue earlier!
